_wandb:
    value:
        cli_version: 0.27.0
        code_path: source-GenDA-GLORYS-train_glorys.py
        e:
            q00nab97xyo91cgm8mm5uiuoqp259qy8:
                codePath: train_glorys.py
                codePathLocal: train_glorys.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "97828376576"
                        used: "21414735872"
                email: nora.mergui@univ-grenoble-alpes.fr
                executable: /home/nora/miniconda3/envs/env_genda/bin/python
                git:
                    commit: e2fc991c39f30354d1798df75099007ea303150a
                    remote: git@github.com:noramergui/Stage-M2-GenDA.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-1dd7bd2e-5a16-2dbc-1f21-f50f01640dae
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-c6349ab2-44be-260f-5535-b239b2ee5523
                host: dibarbox
                memory:
                    total: "540659929088"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/nora/GenDA/train_glorys.py
                python: CPython 3.11.15
                root: /home/nora/GenDA/wandb
                startedAt: "2026-05-29T15:08:50.425139Z"
                writerId: q00nab97xyo91cgm8mm5uiuoqp259qy8
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 13
                - 61
            "4": 3.11.15
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
